root = "."
tmp_dir = "tmp"

[build]
bin = "tmp/main"
cmd = "go build -o ./tmp/main \
  -ldflags=\"-X 'xi/app/lib/cfg.BuildDate=$(date -u +%Y-%m-%dT%H:%M:%SZ )' \
             -X 'xi/app/lib/cfg.BuildRevision=$(git rev-parse --short HEAD)' \
             -X 'xi/app/lib/cfg.BuildVersion=$(git describe --tags --match v*.*.* --abbrev=0 2>/dev/null || echo dev)'\" \
  ./app"
delay = 1000

[log]
time = true
color = true
prefix = "air:"

[watch]
extensions = ["go", "tpl", "tmpl", "html", "toml", "yaml"]
ignore = ["tmp", "vendor", "node_modules"]

[screen]
clear_on_rebuild = true
