version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
