name: Build GO

on:
  workflow_call:
    inputs:
      appName:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build GO Binaries
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o "${{ inputs.appName }}-${{ matrix.goos }}-${{ matrix.goarch }}"
          ls ./ 

      - name: Upload artifact for ${{ matrix.goos }}-${{ matrix.goarch }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.appName }}-${{ matrix.goos }}-${{ matrix.goarch }}
          path: ${{ inputs.appName }}-${{ matrix.goos }}-${{ matrix.goarch }}