name: Release Dev

on:
  push:
    tags:
      - 'v*.*.*'


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: "~> v2"
          args: release --clean --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Release Dev Assets
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: ${{ steps.file_list.outputs.files }}
      #     token: ${{ secrets.GITHUB_TOKEN }}
