name: Release Public

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    uses: ./.github/workflows/build-go.yml
    with:
      appName: ${{ github.event.repository.name }}-${{ github.ref_name }}
      version: ${{ github.ref_name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: app-binaries

      - name: Release Public Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          body: |
            Public release of version ${{ github.ref_name }}.
            See changelog in private repo.
          repository: xet-labs/xi
          token: ${{ secrets.XI_REPO_TOKEN }}
          files: ${{ github.event.repository.name }}-${{ github.ref_name }}-*
