name: Release Nightly

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    # branches:
    #   - nightly

jobs:
  release-nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BuildVerPrepend: nightly

      - name: List release artifacts
        run: |
          echo "All Files:"
          tree --dirsfirst ./dist -l -f -a